### ISSUE TITLE
Browser Configuration Issue

### ISSUE THREAD

**Issue by nzdunic** [Strider-CD/strider-sauce#9]
Hi,

I'm not able to configure browsers for some reason. The browsers screen is empty. Have a missed something?

![strider - saucelabs - integration](https://cloud.githubusercontent.com/assets/922154/4038387/95fdd1ec-2cb4-11e4-921e-94b7235aa4de.png)

Update:  I've since upgraded to the latest StriderCD via npm.  I no longer can see the plugin.  I've tried re-installing the plugin as well and that has not made any difference.

Regards,

Nick

**Comment by knownasilya** [comment]
Issue should be fixed. If it's not, please reopen issue with more details.
